dataset:
  wonders_of_world:
    root_dir: './data/Wonders_of_World'
    n_classes: 12
  pizza_not_pizza:
    root_dir: './data/pizza_not_pizza'
    n_classes: 2

train:
  epochs: 50
  train_batch_size: 64
  test_batch_size: 8
  train_size: 0.7
  val_size: 0.2
  learning_rate: 1.0e-5
  weight_decay: 1.0e-8